package com.brentandjody.mountainunicyclist.data;

import android.provider.BaseColumns;

/**
 * Created by brent on 07/04/15.
 */
public interface IBaseColumns extends BaseColumns {
    /**
     * Rows are never deleted, only marked as such and not shown.
     * <P>Type: INTEGER (boolean)</P>
     * 1 = deleted, 0 = not deleted
     */
    public static final String _FLAGS = "_flags";

    /**
     * An ID generated by the central server
     */
    public static final String _UID = "_uid";

}
